---
- name: Install nginx with Virtual Hosts
  hosts: webservers
  remote_user: runner
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: false

  vars:
      sites:
          - "etis.com"
          - "fizfak.com"
          - "mehmat.ru"

  roles:
      - nginx_vhosts
